name: Merge Rule Lists

on:
  schedule:
    - cron: '0 0 1,16 * *'
  workflow_dispatch:

jobs:
  merge_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download, Merge and Append Rules
      run: |
        > AiandTiktok.list

        curl -sL "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/tiktok.list" >> AiandTiktok.list

        echo "" >> rules.list
        curl -sL "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/category-ai-!cn.list" >> AiandTiktok.list

        echo "" >> rules.list
        echo "IP-CIDR,8.8.8.8/32,no-resolve" >> AiandTiktok.list

        sed -i '/^$/N;/^\n$/D' AiandTiktok.list

    - name: Commit and Push
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add AiandTiktok.list
        git commit -m "Update AiandTiktok.list: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push
