name: Merge Rule Lists

on:
  schedule:
    - cron: '0 0 1,16 * *'
  workflow_dispatch:

jobs:
  merge_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Download, Merge and Append Rules
      run: |
        mkdir -p tmp_rules

        curl -sL "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/tiktok.list" > tmp_rules/file1.list
        sed -i '$a\' tmp_rules/file1.list

        curl -sL "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/refs/heads/meta/geo/geosite/classical/category-ai-!cn.list" > tmp_rules/file2.list
        sed -i '$a\' tmp_rules/file2.list

        echo "IP-CIDR,8.8.8.8/32,no-resolve" > tmp_rules/custom.list
        sed -i '$a\' tmp_rules/custom.list

        cat tmp_rules/file1.list tmp_rules/file2.list tmp_rules/custom.list | sed '/^$/d' > AiandTiktok.list

    - name: Commit and Push
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add AiandTiktok.list
        git commit -m "Update AiandTiktok.list: $(date +'%Y-%m-%d %H:%M:%S')" || exit 0
        git push
