name: Build OpenWrt for H3C NX30Pro

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: false
        default: 'false'
        type: choice
        options:
          - true
          - false
      source_branch:
        description: "Select the source branch"
        required: false
        default: "immortalwrt"
        type: choice
        options:
          - openwrt
          - lede
          - immortalwrt
      openwrt_branch:
        description: "Select the openwrt branch"
        required: false
        default: "openwrt-25.12"
        type: choice
        options:
          - main
          - master
          - openwrt-23.05
          - openwrt-24.10
          - openwrt-25.12
      use_ccache:
        description: "Auto use ccache."
        required: false
        default: true
        type: boolean

env:
  FEEDS_CONF: config/${{ inputs.source_branch }}_${{ inputs.openwrt_branch }}/feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  CCACHE_DIR: /builder/openwrt/.ccache
  UPLOAD_BIN_DIR: false
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Hong_Kong

jobs:
  build:
    runs-on: ubuntu-24.04
    if: ${{ github.event.repository.owner.id == github.event.sender.id }}
    permissions:
      contents: write

    name: build-${{ inputs.openwrt_branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Initialize the build environment
        id: init
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          docker rmi -f $(docker images -q) 2>/dev/null || true
          [[ -n "${AGENT_TOOLSDIRECTORY}" ]] && sudo rm -rf "${AGENT_TOOLSDIRECTORY}"
          sudo rm -rf /usr/share/dotnet /usr/local/lib/android 2>/dev/null
          sudo swapoff -a
          sudo rm -f /swapfile /mnt/swapfile
          sudo -E apt-get -y update
          sudo -E apt-get -y purge azure-cli ghc* zulu* llvm* firefox google* dotnet* powershell openjdk* mongodb* moby* || true
          sudo -E apt-get -y install $(curl -fsSL https://ophub.org/ubuntu2404-make-openwrt-depends)
          sudo -E systemctl daemon-reload
          #sudo -E apt-get -y full-upgrade
          sudo -E apt-get -y autoremove --purge
          sudo -E apt-get clean
          sudo sed -i '/NVM_DIR/d;/skel/d' /root/{.bashrc,.profile}
          sudo rm -rf ~/{.cargo,.dotnet,.rustup}
          sudo -E timedatectl set-timezone "${TZ:-Etc/UTC}"
          sudo -E ntpdate ntp.ubuntu.com 0.pool.ntp.org || true
          sudo -E timedatectl set-ntp true
          date -u
          timedatectl status || true
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Create virtual disk for extended storage
        id: disk
        run: |
          # Get available space in exact GB
          root_avail=$(df --block-size=1G / | tail -1 | awk '{print $4}')
          root_size=$(( root_avail - 4 ))
          [[ "${root_size}" -gt 0 ]] || { echo "Error: Insufficient space on /: ${root_avail}G available"; exit 1; }

          sudo truncate -s "${root_size}"G /root.img
          build_dev=$(sudo losetup --find --show /root.img)
          echo "Using /: ${root_size}G"

          sudo mkfs.xfs -f -i sparse=0 -b size=4096 "${build_dev}"
          sudo mkdir -p /builder
          sudo mount "${build_dev}" /builder
          sudo chown -R runner:runner /builder
          df -Th
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Clone source code [ ${{ inputs.source_branch }}_${{ inputs.openwrt_branch }} ]
        id: codes
        working-directory: /builder
        if: ${{ steps.init.outputs.status == 'success' && !cancelled() }}
        run: |
          if [[ "${{ inputs.source_branch }}" == *"openwrt"* ]]; then
              REPO_URL="https://github.com/openwrt/openwrt"
          elif [[ "${{ inputs.source_branch }}" == *"lede"* ]]; then
              REPO_URL="https://github.com/coolsnowwolf/lede"
          elif [[ "${{ inputs.source_branch }}" == *"immortalwrt"* ]]; then
              REPO_URL="https://github.com/immortalwrt/immortalwrt"
          else
              echo "Unknown source code repository."
              exit 1
          fi
          
          REPO_BRANCH="${{ inputs.openwrt_branch }}"
          REPO_NAME="${{ inputs.source_branch }}"

          git clone -q --single-branch --depth=1 --branch=${REPO_BRANCH} ${REPO_URL} openwrt
          ln -sf /builder/openwrt ${{ github.workspace }}/openwrt

          echo -e "REPO_URL: [ ${REPO_URL} ]\nREPO_BRANCH: [ ${REPO_BRANCH} ]\nREPO_NAME: [ ${REPO_NAME} ]"
          df -hT ${PWD}
          echo "REPO_URL=${REPO_URL}" >> ${GITHUB_ENV}
          echo "REPO_NAME=${REPO_NAME}" >> ${GITHUB_ENV}
          echo "REPO_BRANCH=${REPO_BRANCH}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Load custom feeds
        run: |
          [[ -f "${FEEDS_CONF}" ]] && cp -f ${FEEDS_CONF} openwrt/feeds.conf.default
          chmod +x ${DIY_P1_SH}
          cd openwrt/
          ${{ github.workspace }}/${DIY_P1_SH}

      - name: Update feeds
        run: cd openwrt/ && ./scripts/feeds update -a

      - name: Install feeds
        run: cd openwrt/ && ./scripts/feeds install -a

      - name: SSH connection to Actions
        uses: P3TERX/ssh2actions@main
        if: (github.event.inputs.ssh == 'true' && github.event.inputs.ssh != 'false') || contains(github.event.action, 'ssh')

      - name: Load custom configuration
        run: |
          [[ -d "files" ]] && mv -f files openwrt/files
          [[ -e "${CONFIG_FILE}" ]] && cp -f ${CONFIG_FILE} openwrt/.config
          chmod +x ${DIY_P2_SH}
          cd openwrt/
          ${{ github.workspace }}/${DIY_P2_SH} "${{ inputs.use_ccache }}"

      - name: Download package
        id: package
        run: |
          cd openwrt/
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: Get OpenWrt source commit hash
        id: openwrthash
        run: |
          repo_path="$(echo "${{ env.REPO_URL }}" | awk -F"github.com/" '{print $2}')"
          api_url="https://api.github.com/repos/${repo_path}/git/ref/heads/${{ env.REPO_BRANCH }}"
          source_hash=$(curl -fsSL -m 20 \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              ${api_url} |
              jq -r '.object.sha'
          )
          [[ -z "${source_hash}" || "${source_hash}" == "null" ]] && source_hash="${{ github.sha }}"
          echo "source_hash=${source_hash}" >> ${GITHUB_ENV}
          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Cache ccache
        uses: actions/cache@v5
        with:
          path: |
            /builder/openwrt/.ccache
            /builder/openwrt/staging_dir/host
            /builder/openwrt/staging_dir/toolchain-*
          key: openwrt-${{ env.REPO_NAME }}-${{ env.source_hash }}
          restore-keys: |
            openwrt-${{ env.REPO_NAME }}-

      - name: Compile the OpenWrt firmware
        id: compile
        run: |
          cd openwrt/
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s

          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Organize files
        id: organize
        run: |
          cd ${{ github.workspace }}/openwrt/bin/targets/mediatek/filogic
          rm -rf packages
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV

          echo "status=success" >> ${GITHUB_OUTPUT}

      - name: Upload firmware to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: OpenWrt_NX30Pro_Firmware
          path: ${{ env.FIRMWARE }}
          retention-days: 7
